In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Any results you write to the current directory are saved as output.

In [2]:
dataset = pd.read_csv('mnist_train.csv')
X = dataset.iloc[:, 1:].values
y = dataset.iloc[:, 0].values

In [3]:
X.shape


(42000, 784)

In [4]:
y.shape

(42000,)

In [5]:
X[0]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0, 188, 255,  94,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0, 191, 250, 253,  93,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   

In [6]:
y[0]

1

In [7]:
X[0].shape

(784,)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1, random_state = 42)


In [9]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

/home/nbuser/anaconda3_420/lib/python3.5/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [10]:
y[0:10]

array([1, 0, 1, 4, 0, 0, 7, 3, 5, 3])

In [11]:
from keras.utils import np_utils
y_train = np_utils.to_categorical(y_train)
y_test = np_utils.to_categorical(y_test)


/home/nbuser/anaconda3_420/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
/home/nbuser/anaconda3_420/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:455: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/nbuser/anaconda3_420/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:456: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/nbuser/anaconda3_420/lib/pyth

In [12]:
y_train

array([[0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

In [15]:
## TODO: Declare the batch_size and number of epochs
batch = 10
epochs = 25


In [ ]:
# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout
# Initialising the ANN
classifier = Sequential()
# TODO: Adding the input layer and the first hidden layer

# TODO: Adding the second hidden layer

# TODO: Adding the output layer

# Initialising the ANN
# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 784, activation = 'tanh', input_dim = 784))

# Adding the second hidden layer
classifier.add(Dense(units = 128, activation = 'tanh'))
classifier.add(Dense(units = 128, activation = 'tanh'))
classifier.add(Dropout(0.2))

classifier.add(Dense(units = 64, activation = 'tanh'))
classifier.add(Dense(units = 64, activation = 'tanh'))
classifier.add(Dropout(0.2))

classifier.add(Dense(units = 32, activation = 'tanh'))
classifier.add(Dense(units = 32, activation = 'tanh'))
classifier.add(Dropout(0.05))
# Adding the output layer
classifier.add(Dense(units = 10, activation = 'softmax'))
# Compiling the ANN
classifier.compile(optimizer = 'rmsprop', loss = 'categorical_crossentropy', metrics = ['accuracy'])
# Fitting the ANN to the Training set
history = classifier.fit(X_train, y_train, 
                         validation_data = (X_test, y_test), 
                         batch_size = 28, 
                         epochs = 8)



Train on 37800 samples, validate on 4200 samples
Epoch 1/8
37800/37800 [==============================] - 47s - loss: 0.3617 - acc: 0.9016 - val_loss: 0.2364 - val_acc: 0.9312
Epoch 2/8
37800/37800 [==============================] - 44s - loss: 0.1951 - acc: 0.9470 - val_loss: 0.2010 - val_acc: 0.9443
Epoch 3/8
37184/37800 [============================>.] - ETA: 0s - loss: 0.1435 - acc: 0.9609

## Here is an example of architecture Try out adding more layers and check out the accuracy.

In [ ]:
# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout
# Initialising the ANN
classifier = Sequential()
# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 784, activation = 'tanh', input_dim = 784))

# Adding the second hidden layer
classifier.add(Dense(units = 128, activation = 'tanh'))
classifier.add(Dense(units = 128, activation = 'tanh'))
classifier.add(Dropout(0.2))

classifier.add(Dense(units = 64, activation = 'tanh'))
classifier.add(Dense(units = 64, activation = 'tanh'))
classifier.add(Dropout(0.2))

classifier.add(Dense(units = 32, activation = 'tanh'))
classifier.add(Dense(units = 32, activation = 'tanh'))
classifier.add(Dropout(0.05))
# Adding the output layer
classifier.add(Dense(units = 10, activation = 'softmax'))
# Compiling the ANN
classifier.compile(optimizer = 'rmsprop', loss = 'categorical_crossentropy', metrics = ['accuracy'])
# Fitting the ANN to the Training set
history = classifier.fit(X_train, y_train, 
                         validation_data = (X_test, y_test), 
                         batch_size = 28, 
                         epochs = 25)



In [19]:
model_acc = classifier.evaluate(X_test, y_test)
print(" Model Accuracy is : {0:.1f}%".format(model_acc[1]*100))


4032/4200 [===========================>..] - ETA: 0s Model Accuracy is : 96.7%


In [20]:
test_dataset = pd.read_csv('mnist_test.csv')

In [21]:
test_dataset.head()

pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0       0       0       0       0       0       0       0       0       0   
1       0       0       0       0       0       0       0       0       0   
2       0       0       0       0       0       0       0       0       0   
3       0       0       0       0       0       0       0       0       0   
4       0       0       0       0       0       0       0       0       0   

   pixel9    ...     pixel774  pixel775  pixel776  pixel777  pixel778  \
0       0    ...            0         0         0         0         0   
1       0    ...            0         0         0         0         0   
2       0    ...            0         0         0         0         0   
3       0    ...            0         0         0         0         0   
4       0    ...            0         0         0         0         0   

   pixel779  pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0         0  
1         0         0         0         0         0  
2         0         0         0         0         0  
3         0         0         0         0         0  
4         0         0         0         0         0  

[5 rows x 784 columns]

In [22]:
test_dataset.shape

(28000, 784)

In [23]:
test = test_dataset.iloc[:,:].values

test=test.reshape(test_dataset.shape[0],784)
test.shape

(28000, 784)

In [24]:
#test = test_dataset.iloc[:,:]
# Prediction
test_pred = classifier.predict(test)
# Mark probability score > 0.5 as Predicted Label, axis = 1 means insert column-wise , 
# you can change the threshold 

In [25]:
results = test_pred.argmax(axis=1)

In [26]:
results = pd.Series(results,name="Label")
submission = pd.concat([pd.Series(range(1,28001),name = "ImageId"),results],axis = 1)
submission.to_csv("solution.csv",index=False)

## Try to submit the results in Kaggle competition let us know your rank .

https://www.kaggle.com/c/digit-recognizer

